### ISSUE TITLE
API: Root route

### ISSUE THREAD

**Issue by ChuckLangford** [ChuckLangford/node-layout#1]
AC:

- expose one route for root
- install express
- create uniquely identifiable rabbitmq messages
- respond to uniquely identifiable rabbitmq messages
- send result back to client
- validate the posted object from the client based on configuration
- valid paths are: login, create, and person
- add documentation that we may want to validate the ops per path

The posted object should look similar to:
```
{
  op: 'get',
  path: 'login',
  context: {}
}
```

**Comment by johnrhampton** [comment]
@ChuckLangford thinking of renaming our api from _api1_ to _express_ or something else.  Thoughts?

**Comment by ChuckLangford** [comment]
Definitely needs a rename. The example api surrounds login/auth yes? Something along those lines? I could be convinced of PROCESS; maybe not so much PLATFORM though. Just thinking from a developers first look at the code.

**Comment by johnrhampton** [comment]
Agreed, on PROCESS over PLATFORM.  

For the api rename, should we go super basic and name it _root_ or something equivalent?  Based on our AC, this would be the API that ruled them all.

**Comment by ChuckLangford** [comment]
Good point. Super basic to start; fancy later.

**Comment by johnrhampton** [comment]
If I was into things, which I'm not, fancy would be neat.

**Comment by ChuckLangford** [comment]
Fancy has been considered; nothing more; nothing less.

**Comment by ChuckLangford** [comment]
@johnrhampton I'm about to submit a PR into your adds-express branch. It's absolutely not necessary for you to accept it (or even like it). I saw a question in your code that I thought I could go ahead and answer for you. To be clear, this is the thing I felt might have been too much. It might still be but, at the very least, this PR proves it is possible. Send me any questions. PR incoming.

**Comment by ChuckLangford** [comment]
Might call root the gateway: http://microservices.io/patterns/apigateway.html
